version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-rest-api"
s3_bucket = "dbb-aws-sam-artifacts"
s3_prefix = "sam-rest-api"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
